### ISSUE TITLE
Dapat menggunakan Set<T>

### ISSUE THREAD

**Issue by piinalpin** [magusabdul/Java-Springboot_Agus-Abdul-Malik#1]
https://github.com/magusabdul/Java-Springboot_Agus-Abdul-Malik/blob/9bfde33f0abb8436d6f9d404ef0d305a2c7d01a7/6_Collections(Iterable)%20dan%207_Collections(Map)/praktikum/Task1.java#L27-L35

**Comment by magusabdul** [comment]
Makasih mas, saya coba
